// Code generated by MockGen. DO NOT EDIT.
// Source: waterfall-backend/internal/modules/services/fs/i_fs (interfaces: IBucketCreator)

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	models "waterfall-backend/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockIBucketCreator is a mock of IBucketCreator interface.
type MockIBucketCreator struct {
	ctrl     *gomock.Controller
	recorder *MockIBucketCreatorMockRecorder
}

// MockIBucketCreatorMockRecorder is the mock recorder for MockIBucketCreator.
type MockIBucketCreatorMockRecorder struct {
	mock *MockIBucketCreator
}

// NewMockIBucketCreator creates a new mock instance.
func NewMockIBucketCreator(ctrl *gomock.Controller) *MockIBucketCreator {
	mock := &MockIBucketCreator{ctrl: ctrl}
	mock.recorder = &MockIBucketCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBucketCreator) EXPECT() *MockIBucketCreatorMockRecorder {
	return m.recorder
}

// CreateBucket mocks base method.
func (m *MockIBucketCreator) CreateBucket(arg0 context.Context, arg1 *models.ObjectRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockIBucketCreatorMockRecorder) CreateBucket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockIBucketCreator)(nil).CreateBucket), arg0, arg1)
}
