// Code generated by ent, DO NOT EDIT.

package seedmigrations

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the seedmigrations type in the database.
	Label = "seed_migrations"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMigrated holds the string denoting the migrated field in the database.
	FieldMigrated = "migrated"
	// Table holds the table name of the seedmigrations in the database.
	Table = "db_seed_migrations"
)

// Columns holds all SQL columns for seedmigrations fields.
var Columns = []string{
	FieldID,
	FieldMigrated,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "waterfall-backend/internal/modules/stores/db/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
)

// Order defines the ordering method for the SeedMigrations queries.
type Order func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMigrated orders the results by the migrated field.
func ByMigrated(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldMigrated, opts...).ToFunc()
}
