// Code generated by ent, DO NOT EDIT.

package seedmigrations

import (
	"waterfall-backend/internal/modules/stores/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldLTE(FieldID, id))
}

// Migrated applies equality check predicate on the "migrated" field. It's identical to MigratedEQ.
func Migrated(v int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldEQ(FieldMigrated, v))
}

// MigratedEQ applies the EQ predicate on the "migrated" field.
func MigratedEQ(v int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldEQ(FieldMigrated, v))
}

// MigratedNEQ applies the NEQ predicate on the "migrated" field.
func MigratedNEQ(v int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldNEQ(FieldMigrated, v))
}

// MigratedIn applies the In predicate on the "migrated" field.
func MigratedIn(vs ...int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldIn(FieldMigrated, vs...))
}

// MigratedNotIn applies the NotIn predicate on the "migrated" field.
func MigratedNotIn(vs ...int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldNotIn(FieldMigrated, vs...))
}

// MigratedGT applies the GT predicate on the "migrated" field.
func MigratedGT(v int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldGT(FieldMigrated, v))
}

// MigratedGTE applies the GTE predicate on the "migrated" field.
func MigratedGTE(v int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldGTE(FieldMigrated, v))
}

// MigratedLT applies the LT predicate on the "migrated" field.
func MigratedLT(v int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldLT(FieldMigrated, v))
}

// MigratedLTE applies the LTE predicate on the "migrated" field.
func MigratedLTE(v int) predicate.SeedMigrations {
	return predicate.SeedMigrations(sql.FieldLTE(FieldMigrated, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SeedMigrations) predicate.SeedMigrations {
	return predicate.SeedMigrations(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SeedMigrations) predicate.SeedMigrations {
	return predicate.SeedMigrations(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SeedMigrations) predicate.SeedMigrations {
	return predicate.SeedMigrations(func(s *sql.Selector) {
		p(s.Not())
	})
}
