// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"waterfall-backend/internal/modules/stores/db/ent/migrations"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MigrationsCreate is the builder for creating a Migrations entity.
type MigrationsCreate struct {
	config
	mutation *MigrationsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetMigrated sets the "migrated" field.
func (mc *MigrationsCreate) SetMigrated(i int) *MigrationsCreate {
	mc.mutation.SetMigrated(i)
	return mc
}

// Mutation returns the MigrationsMutation object of the builder.
func (mc *MigrationsCreate) Mutation() *MigrationsMutation {
	return mc.mutation
}

// Save creates the Migrations in the database.
func (mc *MigrationsCreate) Save(ctx context.Context) (*Migrations, error) {
	return withHooks[*Migrations, MigrationsMutation](ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MigrationsCreate) SaveX(ctx context.Context) *Migrations {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MigrationsCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MigrationsCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MigrationsCreate) check() error {
	if _, ok := mc.mutation.Migrated(); !ok {
		return &ValidationError{Name: "migrated", err: errors.New(`ent: missing required field "Migrations.migrated"`)}
	}
	return nil
}

func (mc *MigrationsCreate) sqlSave(ctx context.Context) (*Migrations, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MigrationsCreate) createSpec() (*Migrations, *sqlgraph.CreateSpec) {
	var (
		_node = &Migrations{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(migrations.Table, sqlgraph.NewFieldSpec(migrations.FieldID, field.TypeInt))
	)
	_spec.OnConflict = mc.conflict
	if value, ok := mc.mutation.Migrated(); ok {
		_spec.SetField(migrations.FieldMigrated, field.TypeInt, value)
		_node.Migrated = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Migrations.Create().
//		SetMigrated(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MigrationsUpsert) {
//			SetMigrated(v+v).
//		}).
//		Exec(ctx)
func (mc *MigrationsCreate) OnConflict(opts ...sql.ConflictOption) *MigrationsUpsertOne {
	mc.conflict = opts
	return &MigrationsUpsertOne{
		create: mc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Migrations.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mc *MigrationsCreate) OnConflictColumns(columns ...string) *MigrationsUpsertOne {
	mc.conflict = append(mc.conflict, sql.ConflictColumns(columns...))
	return &MigrationsUpsertOne{
		create: mc,
	}
}

type (
	// MigrationsUpsertOne is the builder for "upsert"-ing
	//  one Migrations node.
	MigrationsUpsertOne struct {
		create *MigrationsCreate
	}

	// MigrationsUpsert is the "OnConflict" setter.
	MigrationsUpsert struct {
		*sql.UpdateSet
	}
)

// SetMigrated sets the "migrated" field.
func (u *MigrationsUpsert) SetMigrated(v int) *MigrationsUpsert {
	u.Set(migrations.FieldMigrated, v)
	return u
}

// UpdateMigrated sets the "migrated" field to the value that was provided on create.
func (u *MigrationsUpsert) UpdateMigrated() *MigrationsUpsert {
	u.SetExcluded(migrations.FieldMigrated)
	return u
}

// AddMigrated adds v to the "migrated" field.
func (u *MigrationsUpsert) AddMigrated(v int) *MigrationsUpsert {
	u.Add(migrations.FieldMigrated, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Migrations.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MigrationsUpsertOne) UpdateNewValues() *MigrationsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Migrations.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MigrationsUpsertOne) Ignore() *MigrationsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MigrationsUpsertOne) DoNothing() *MigrationsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MigrationsCreate.OnConflict
// documentation for more info.
func (u *MigrationsUpsertOne) Update(set func(*MigrationsUpsert)) *MigrationsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MigrationsUpsert{UpdateSet: update})
	}))
	return u
}

// SetMigrated sets the "migrated" field.
func (u *MigrationsUpsertOne) SetMigrated(v int) *MigrationsUpsertOne {
	return u.Update(func(s *MigrationsUpsert) {
		s.SetMigrated(v)
	})
}

// AddMigrated adds v to the "migrated" field.
func (u *MigrationsUpsertOne) AddMigrated(v int) *MigrationsUpsertOne {
	return u.Update(func(s *MigrationsUpsert) {
		s.AddMigrated(v)
	})
}

// UpdateMigrated sets the "migrated" field to the value that was provided on create.
func (u *MigrationsUpsertOne) UpdateMigrated() *MigrationsUpsertOne {
	return u.Update(func(s *MigrationsUpsert) {
		s.UpdateMigrated()
	})
}

// Exec executes the query.
func (u *MigrationsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MigrationsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MigrationsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MigrationsUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MigrationsUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MigrationsCreateBulk is the builder for creating many Migrations entities in bulk.
type MigrationsCreateBulk struct {
	config
	builders []*MigrationsCreate
	conflict []sql.ConflictOption
}

// Save creates the Migrations entities in the database.
func (mcb *MigrationsCreateBulk) Save(ctx context.Context) ([]*Migrations, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Migrations, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MigrationsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MigrationsCreateBulk) SaveX(ctx context.Context) []*Migrations {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MigrationsCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MigrationsCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Migrations.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MigrationsUpsert) {
//			SetMigrated(v+v).
//		}).
//		Exec(ctx)
func (mcb *MigrationsCreateBulk) OnConflict(opts ...sql.ConflictOption) *MigrationsUpsertBulk {
	mcb.conflict = opts
	return &MigrationsUpsertBulk{
		create: mcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Migrations.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (mcb *MigrationsCreateBulk) OnConflictColumns(columns ...string) *MigrationsUpsertBulk {
	mcb.conflict = append(mcb.conflict, sql.ConflictColumns(columns...))
	return &MigrationsUpsertBulk{
		create: mcb,
	}
}

// MigrationsUpsertBulk is the builder for "upsert"-ing
// a bulk of Migrations nodes.
type MigrationsUpsertBulk struct {
	create *MigrationsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Migrations.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MigrationsUpsertBulk) UpdateNewValues() *MigrationsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Migrations.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MigrationsUpsertBulk) Ignore() *MigrationsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MigrationsUpsertBulk) DoNothing() *MigrationsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MigrationsCreateBulk.OnConflict
// documentation for more info.
func (u *MigrationsUpsertBulk) Update(set func(*MigrationsUpsert)) *MigrationsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MigrationsUpsert{UpdateSet: update})
	}))
	return u
}

// SetMigrated sets the "migrated" field.
func (u *MigrationsUpsertBulk) SetMigrated(v int) *MigrationsUpsertBulk {
	return u.Update(func(s *MigrationsUpsert) {
		s.SetMigrated(v)
	})
}

// AddMigrated adds v to the "migrated" field.
func (u *MigrationsUpsertBulk) AddMigrated(v int) *MigrationsUpsertBulk {
	return u.Update(func(s *MigrationsUpsert) {
		s.AddMigrated(v)
	})
}

// UpdateMigrated sets the "migrated" field to the value that was provided on create.
func (u *MigrationsUpsertBulk) UpdateMigrated() *MigrationsUpsertBulk {
	return u.Update(func(s *MigrationsUpsert) {
		s.UpdateMigrated()
	})
}

// Exec executes the query.
func (u *MigrationsUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MigrationsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MigrationsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MigrationsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
