// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"
	"waterfall-backend/internal/modules/stores/db/ent/chapter"
	"waterfall-backend/internal/modules/stores/db/ent/part"
	"waterfall-backend/internal/modules/stores/db/ent/predicate"
	"waterfall-backend/internal/modules/stores/db/ent/release"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PartQuery is the builder for querying Part entities.
type PartQuery struct {
	config
	ctx          *QueryContext
	order        []part.Order
	inters       []Interceptor
	predicates   []predicate.Part
	withChapters *ChapterQuery
	withRelease  *ReleaseQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PartQuery builder.
func (pq *PartQuery) Where(ps ...predicate.Part) *PartQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit the number of records to be returned by this query.
func (pq *PartQuery) Limit(limit int) *PartQuery {
	pq.ctx.Limit = &limit
	return pq
}

// Offset to start from.
func (pq *PartQuery) Offset(offset int) *PartQuery {
	pq.ctx.Offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *PartQuery) Unique(unique bool) *PartQuery {
	pq.ctx.Unique = &unique
	return pq
}

// Order specifies how the records should be ordered.
func (pq *PartQuery) Order(o ...part.Order) *PartQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryChapters chains the current query on the "chapters" edge.
func (pq *PartQuery) QueryChapters() *ChapterQuery {
	query := (&ChapterClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(part.Table, part.FieldID, selector),
			sqlgraph.To(chapter.Table, chapter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, part.ChaptersTable, part.ChaptersColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRelease chains the current query on the "release" edge.
func (pq *PartQuery) QueryRelease() *ReleaseQuery {
	query := (&ReleaseClient{config: pq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(part.Table, part.FieldID, selector),
			sqlgraph.To(release.Table, release.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, part.ReleaseTable, part.ReleaseColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Part entity from the query.
// Returns a *NotFoundError when no Part was found.
func (pq *PartQuery) First(ctx context.Context) (*Part, error) {
	nodes, err := pq.Limit(1).All(setContextOp(ctx, pq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{part.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *PartQuery) FirstX(ctx context.Context) *Part {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Part ID from the query.
// Returns a *NotFoundError when no Part ID was found.
func (pq *PartQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pq.Limit(1).IDs(setContextOp(ctx, pq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{part.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *PartQuery) FirstIDX(ctx context.Context) string {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Part entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Part entity is found.
// Returns a *NotFoundError when no Part entities are found.
func (pq *PartQuery) Only(ctx context.Context) (*Part, error) {
	nodes, err := pq.Limit(2).All(setContextOp(ctx, pq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{part.Label}
	default:
		return nil, &NotSingularError{part.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *PartQuery) OnlyX(ctx context.Context) *Part {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Part ID in the query.
// Returns a *NotSingularError when more than one Part ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *PartQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = pq.Limit(2).IDs(setContextOp(ctx, pq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{part.Label}
	default:
		err = &NotSingularError{part.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *PartQuery) OnlyIDX(ctx context.Context) string {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Parts.
func (pq *PartQuery) All(ctx context.Context) ([]*Part, error) {
	ctx = setContextOp(ctx, pq.ctx, "All")
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Part, *PartQuery]()
	return withInterceptors[[]*Part](ctx, pq, qr, pq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pq *PartQuery) AllX(ctx context.Context) []*Part {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Part IDs.
func (pq *PartQuery) IDs(ctx context.Context) (ids []string, err error) {
	if pq.ctx.Unique == nil && pq.path != nil {
		pq.Unique(true)
	}
	ctx = setContextOp(ctx, pq.ctx, "IDs")
	if err = pq.Select(part.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *PartQuery) IDsX(ctx context.Context) []string {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *PartQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pq.ctx, "Count")
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pq, querierCount[*PartQuery](), pq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pq *PartQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *PartQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pq.ctx, "Exist")
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *PartQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PartQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *PartQuery) Clone() *PartQuery {
	if pq == nil {
		return nil
	}
	return &PartQuery{
		config:       pq.config,
		ctx:          pq.ctx.Clone(),
		order:        append([]part.Order{}, pq.order...),
		inters:       append([]Interceptor{}, pq.inters...),
		predicates:   append([]predicate.Part{}, pq.predicates...),
		withChapters: pq.withChapters.Clone(),
		withRelease:  pq.withRelease.Clone(),
		// clone intermediate query.
		sql:  pq.sql.Clone(),
		path: pq.path,
	}
}

// WithChapters tells the query-builder to eager-load the nodes that are connected to
// the "chapters" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PartQuery) WithChapters(opts ...func(*ChapterQuery)) *PartQuery {
	query := (&ChapterClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withChapters = query
	return pq
}

// WithRelease tells the query-builder to eager-load the nodes that are connected to
// the "release" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PartQuery) WithRelease(opts ...func(*ReleaseQuery)) *PartQuery {
	query := (&ReleaseClient{config: pq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pq.withRelease = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Part.Query().
//		GroupBy(part.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *PartQuery) GroupBy(field string, fields ...string) *PartGroupBy {
	pq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PartGroupBy{build: pq}
	grbuild.flds = &pq.ctx.Fields
	grbuild.label = part.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Part.Query().
//		Select(part.FieldCreatedAt).
//		Scan(ctx, &v)
func (pq *PartQuery) Select(fields ...string) *PartSelect {
	pq.ctx.Fields = append(pq.ctx.Fields, fields...)
	sbuild := &PartSelect{PartQuery: pq}
	sbuild.label = part.Label
	sbuild.flds, sbuild.scan = &pq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PartSelect configured with the given aggregations.
func (pq *PartQuery) Aggregate(fns ...AggregateFunc) *PartSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *PartQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pq); err != nil {
				return err
			}
		}
	}
	for _, f := range pq.ctx.Fields {
		if !part.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	if part.Policy == nil {
		return errors.New("ent: uninitialized part.Policy (forgotten import ent/runtime?)")
	}
	if err := part.Policy.EvalQuery(ctx, pq); err != nil {
		return err
	}
	return nil
}

func (pq *PartQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Part, error) {
	var (
		nodes       = []*Part{}
		_spec       = pq.querySpec()
		loadedTypes = [2]bool{
			pq.withChapters != nil,
			pq.withRelease != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Part).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Part{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withChapters; query != nil {
		if err := pq.loadChapters(ctx, query, nodes,
			func(n *Part) { n.Edges.Chapters = []*Chapter{} },
			func(n *Part, e *Chapter) { n.Edges.Chapters = append(n.Edges.Chapters, e) }); err != nil {
			return nil, err
		}
	}
	if query := pq.withRelease; query != nil {
		if err := pq.loadRelease(ctx, query, nodes, nil,
			func(n *Part, e *Release) { n.Edges.Release = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *PartQuery) loadChapters(ctx context.Context, query *ChapterQuery, nodes []*Part, init func(*Part), assign func(*Part, *Chapter)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Part)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.Chapter(func(s *sql.Selector) {
		s.Where(sql.InValues(part.ChaptersColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PartUUID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "part_uuid" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *PartQuery) loadRelease(ctx context.Context, query *ReleaseQuery, nodes []*Part, init func(*Part), assign func(*Part, *Release)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Part)
	for i := range nodes {
		if nodes[i].ReleaseUUID == nil {
			continue
		}
		fk := *nodes[i].ReleaseUUID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(release.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "release_uuid" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pq *PartQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	_spec.Node.Columns = pq.ctx.Fields
	if len(pq.ctx.Fields) > 0 {
		_spec.Unique = pq.ctx.Unique != nil && *pq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *PartQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(part.Table, part.Columns, sqlgraph.NewFieldSpec(part.FieldID, field.TypeString))
	_spec.From = pq.sql
	if unique := pq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pq.path != nil {
		_spec.Unique = true
	}
	if fields := pq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, part.FieldID)
		for i := range fields {
			if fields[i] != part.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if pq.withRelease != nil {
			_spec.Node.AddColumnOnce(part.FieldReleaseUUID)
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *PartQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(part.Table)
	columns := pq.ctx.Fields
	if len(columns) == 0 {
		columns = part.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.ctx.Unique != nil && *pq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range pq.modifiers {
		m(selector)
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pq *PartQuery) Modify(modifiers ...func(s *sql.Selector)) *PartSelect {
	pq.modifiers = append(pq.modifiers, modifiers...)
	return pq.Select()
}

// PartGroupBy is the group-by builder for Part entities.
type PartGroupBy struct {
	selector
	build *PartQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *PartGroupBy) Aggregate(fns ...AggregateFunc) *PartGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the selector query and scans the result into the given value.
func (pgb *PartGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pgb.build.ctx, "GroupBy")
	if err := pgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PartQuery, *PartGroupBy](ctx, pgb.build, pgb, pgb.build.inters, v)
}

func (pgb *PartGroupBy) sqlScan(ctx context.Context, root *PartQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pgb.flds)+len(pgb.fns))
		for _, f := range *pgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PartSelect is the builder for selecting fields of Part entities.
type PartSelect struct {
	*PartQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *PartSelect) Aggregate(fns ...AggregateFunc) *PartSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *PartSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ps.ctx, "Select")
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PartQuery, *PartSelect](ctx, ps.PartQuery, ps, ps.inters, v)
}

func (ps *PartSelect) sqlScan(ctx context.Context, root *PartQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ps *PartSelect) Modify(modifiers ...func(s *sql.Selector)) *PartSelect {
	ps.modifiers = append(ps.modifiers, modifiers...)
	return ps
}
