// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chapter is the predicate function for chapter builders.
type Chapter func(*sql.Selector)

// ChapterText is the predicate function for chaptertext builders.
type ChapterText func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Migrations is the predicate function for migrations builders.
type Migrations func(*sql.Selector)

// Part is the predicate function for part builders.
type Part func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Release is the predicate function for release builders.
type Release func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// SeedMigrations is the predicate function for seedmigrations builders.
type SeedMigrations func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
